import mike from './tileImages/mike.png';
import messi from './tileImages/Messi.png';
import nap from './tileImages/Nap.png';
import caeser from './tileImages/Caeser.png';
import london from './tileImages/London.png';
import seoul from './tileImages/Seoul.png';
import golf from './tileImages/Golf.png';
import nike from './tileImages/Nike.png';
import china from './tileImages/China.png';
import phelps from './tileImages/Phelps.png';
export const tileArray = [
    {name:"Michael Jordan",src:mike,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Messi",src:messi,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Napoleon",src:nap,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Julius Caeser",src:caeser,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"London",src:london,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Seoul",src:seoul,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Golf",src:golf,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Nike",src:nike,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"China",src:china,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},
    {name:"Michael Phelps",src:phelps,link:"./Michael-Jordan",overview:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."},

]/***
export const tileArray = [
    ["Michael Jordan","./tileImages/mike.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Messi","./tileImages/Messi.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Napoleon","./tileImages/Nap.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Julius Caeser","./tileImages/Caeser.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["London","./tileImages/London.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Seoul","./tileImages/Seoul.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Golf","./tileImages/Golf.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Nike","./tileImages/Nike.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["China","./tileImages/China.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],
    ["Michael Phelps","./tileImages/Phelps.png","./Michael-Jordan","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean est justo, ultricies eget suscipit sit amet, vulputate sit amet ex. Vivamus accumsan pellentesque neque, ut aliquam turpis pellentesque ut. Nullam eu rhoncus sapien. Nullam suscipit quam ut dui cursus, egestas efficitur metus congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed laoreet justo tellus, in maximus est finibus sit amet. Maecenas interdum quam vitae ipsum mollis dictum. Phasellus consectetur ullamcorper mauris ut pharetra. Integer ut interdum risus. Suspendisse sapien arcu, iaculis in semper eget, convallis vel massa. Sed vel orci sodales, scelerisque lacus elementum, ornare mi. Quisque porttitor bibendum hendrerit."],

]***/